"""Configuration centralisée de kubic-cli.

Ordre de priorité pour chaque clé :
1. Variable d'environnement spécifique (ex : KUBIC_CLI_YAML_HEADER)
2. Valeur définie dans un fichier *config.toml*
3. Valeur de repli codée en dur

Le chemin du fichier TOML peut être précisé via KUBIC_CLI_CONFIG, sinon
~/.config/kubic-cli/config.toml est utilisé.
"""

import os
from pathlib import Path
from typing import Any, Dict

# ---------------------------------------------------------------------------
# Chargement du fichier TOML
# ---------------------------------------------------------------------------

try:
    import tomllib  # Python ≥3.11
except ModuleNotFoundError:  # pragma: no cover – fallback pour Python <3.11
    import tomli as tomllib  # type: ignore


def _load_toml(path: Path) -> Dict[str, Any]:
    if path.exists():
        try:
            return tomllib.loads(path.read_text())  # type: ignore[arg-type]
        except Exception:
            pass  # fichier corrompu ? on ignore et retourne vide
    return {}


CONFIG_PATH: Path = Path(os.getenv("KUBIC_CLI_CONFIG", "~/.config/kubic-cli/config.toml")).expanduser()
_TOML_DATA: Dict[str, Any] = _load_toml(CONFIG_PATH)


def _cfg(key: str, env: str, default: Any) -> Any:
    """Retourne la valeur avec la priorité env > toml > default."""
    if env_val := os.getenv(env):
        return env_val
    if key in _TOML_DATA:
        return _TOML_DATA[key]
    return default


# ---------------------------------------------------------------------------
# Paramètres exposés
# ---------------------------------------------------------------------------

YAML_HEADER: str = _cfg("yaml_header", "KUBIC_CLI_YAML_HEADER", "# Generated by kubic-cli\n")

DEFAULT_GITOPS_PATH: Path = Path(_cfg("gitops_path", "KUBIC_CLI_GITOPS_PATH", "shared-k8s-prd"))

# URL de l'instance Password Pusher (endpoint /p.json). Permet d'utiliser une instance auto-hébergée.
PW_PUSH_URL: str = _cfg("pw_push_url", "KUBIC_CLI_PWPUSH_URL", "https://pwpush.com/p.json")

__all__ = [
    "YAML_HEADER",
    "DEFAULT_GITOPS_PATH",
    "PW_PUSH_URL",
    "CONFIG_PATH",
]
