from pathlib import Path
from typing import List
import typer

__all__ = ["ensure_account", "ensure_rbac"]


def ensure_account(cm_path: Path, user: str):
    """Ajoute accounts.<user>: apiKey,login dans argocd-cm."""
    if not cm_path.exists():
        typer.secho(f"[WARN] {cm_path} introuvable, compte {user} ignoré", fg=typer.colors.YELLOW)
        return

    text = cm_path.read_text()
    if f"accounts.{user}:" in text:
        return

    lines = text.splitlines(keepends=True)
    insert_idx = next((i for i,l in enumerate(lines) if l.startswith("  accounts.")), None)
    if insert_idx is None:
        insert_idx = next((i for i,l in enumerate(lines) if l.strip()=="data:"), None)
    if insert_idx is None:
        typer.secho("[ERROR] Impossible d'insérer le compte dans argocd-cm", fg=typer.colors.RED)
        return

    account_block = f"  # generated by kubic-cli\n  accounts.{user}: apiKey,login\n"
    lines.insert(insert_idx+1, account_block)
    cm_path.write_text("".join(lines))
    typer.echo(f"[UPDATE] Compte {user} ajouté dans argocd-cm.yaml")


def ensure_rbac(rbac_path: Path, slug: str, devs: List[str]):
    """Garantit que le rôle projet et mappings g,<user>,role existent."""
    if not rbac_path.exists():
        typer.secho(f"[WARN] {rbac_path} introuvable, RBAC non modifié", fg=typer.colors.YELLOW)
        return

    lines = rbac_path.read_text().splitlines(keepends=True)
    indent = "    "
    role_present = any(f"role:{slug}, applications" in l for l in lines)

    modified = False
    if not role_present:
        block = ["\n", f"{indent}# Auto-generated for {slug} – kubic-cli\n"]
        for verb in ["create","delete","get","override","sync","update"]:
            block.append(f"{indent}p, role:{slug}, applications, {verb}, default/{slug}*, allow\n")
        block.append(f"{indent}g, {slug}, role:{slug}\n")
        for dev in devs:
            block.append(f"{indent}g, {dev}, role:{slug}\n")
        lines.extend(block)
        modified = True
    else:
        for dev in devs:
            map_line = f"{indent}g, {dev}, role:{slug}\n"
            if not any(map_line.strip()==l.strip() for l in lines):
                lines.append(map_line)
                modified = True
    if modified:
        rbac_path.write_text("".join(lines))
        typer.echo(f"[UPDATE] RBAC mis à jour pour {slug}")
